In [1]:
import numpy as np

In [4]:
lst=[1,2,3,4]

In [7]:
a=np.array(lst)

In [8]:
a

array([1, 2, 3, 4])

In [10]:
a.shape #### it is single dimension

(4,)

In [15]:
nested_list=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [16]:
b=np.array(nested_list)

In [17]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
b.shape

(4, 3)

In [19]:
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
b.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [21]:
b.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [23]:
np.array(['bjhbj',1,2,3])

array(['bjhbj', '1', '2', '3'], dtype='<U5')

In [27]:
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [29]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [31]:
np.array([1,2,3],dtype='int64')

array([1, 2, 3], dtype=int64)

In [32]:
np.array([1,2,3],dtype=np.float)

array([1., 2., 3.])

In [33]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
b[2]

array([7, 8, 9])

In [35]:
b[2][2]

9

In [36]:
b[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [37]:
b[1:3,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [38]:
b[1:3,1:]

array([[5, 6],
       [8, 9]])

In [42]:
b[1:3,[0,-1]]

array([[4, 6],
       [7, 9]])

In [55]:
b[[0,3],[0,2]]

array([ 1, 12])

In [56]:
np.mat([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [57]:
np.mat(np.array([1,2,3,4,5]))

matrix([[1, 2, 3, 4, 5]])

In [63]:
issubclass(np.matrix,np.ndarray)

True

In [68]:
arr2=np.asarray([12,34,5])

In [69]:
arr1=np.array([12,34,5])

In [67]:
type(np.array([12,34,5]))

numpy.ndarray

In [ ]:
## asarray,array diffrence

In [70]:
arr1==arr2

array([ True,  True,  True])

In [71]:
arr1 is arr2 ### F because diffrnt memory locations.

False

In [ ]:
#### "is" is used to test if two varbls belong to the same object

In [72]:
a=10
b=10
a is b
## it is true because they both have the same  object "int" 

True

In [73]:
arr3=arr1

In [74]:
arr3[0]

12

In [77]:
a=370
b=370
a is b
## is is false because 

False

In [78]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [80]:
a=lambda i,j: i==j

In [79]:
np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [81]:
np.fromfunction(lambda i,j: i*j,(3,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [82]:
a=np.array([1,2,3,4])
b=a

In [83]:
b[0]=22

In [84]:
a

array([22,  2,  3,  4])

In [85]:
b=a.copy()

In [86]:
b

array([22,  2,  3,  4])

In [87]:
b[1]=12

In [88]:
a

array([22,  2,  3,  4])

In [89]:
c=np.array((5,4,3,1))
c

array([5, 4, 3, 1])

In [90]:
c[2]=20

In [91]:
c

array([ 5,  4, 20,  1])

In [98]:
str1='ineuron'
str1[0:7:2]

'iern'

In [ ]:
## is vs == _
## np.array 
# np.asarray
# np.asanyarray

In [99]:
lst1=["k1","k2","k3"]
lst2=["k1","k2","k3"]
lst1==lst2 #_is creating in the same memory location

True

In [100]:
lst1 is lst2

False

In [101]:
lst3=lst1
lst3 is lst1

True

In [102]:
a=10
b=10
a is b

True

In [103]:
### Shallow copy vs deep copy
a=np.array([1,2,3,4])
b=a

In [104]:
b

array([1, 2, 3, 4])

In [105]:
b[0]=5

In [106]:
b

array([5, 2, 3, 4])

In [107]:
a

array([5, 2, 3, 4])

In [ ]:
## Shallow Copy
### b is reffering to a, changes made in b is reffering the changes in a.

In [109]:
c=a.copy()
c  
# Deep copy
# this creats the same array in diffnt memory location

array([5, 2, 3, 4])

In [113]:
a=np.array([1,2,3,4])
np.asarray(a) is a ### this refers to the same memory location

True

In [114]:
np.array(a) is a

False

In [116]:
a=258
b=258
a is b

False

In [118]:
np.asanyarray(a) is a

False